// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api.tsx";
import * as $4 from "./routes/api/audio.ts";
import * as $5 from "./routes/api/feedback.ts";
import * as $6 from "./routes/api/joke.ts";
import * as $7 from "./routes/feedback.tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/API.tsx";
import * as $$1 from "./islands/Code.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/FeedbackForm.tsx";
import * as $$4 from "./islands/Form.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api.tsx": $3,
    "./routes/api/audio.ts": $4,
    "./routes/api/feedback.ts": $5,
    "./routes/api/joke.ts": $6,
    "./routes/feedback.tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/API.tsx": $$0,
    "./islands/Code.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/FeedbackForm.tsx": $$3,
    "./islands/Form.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
